### ISSUE TITLE
'PPOTFPolicy' object has no attribute 'sess'

### ISSUE THREAD

**Issue by mengzili** [neurocuts/neurocuts#1]
Hi, 

I've encountered the following problem when running `python run_neurocuts.py --rules=acl5_1k --fast`.
```
2019-07-11 10:41:34,029	ERROR trial_runner.py:487 -- Error processing event.
Traceback (most recent call last):
  File "/home/mengzl/miniconda3/envs/neurocuts/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 436, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/mengzl/miniconda3/envs/neurocuts/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 323, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/mengzl/miniconda3/envs/neurocuts/lib/python3.5/site-packages/ray/worker.py", line 2195, in get
    raise value
ray.exceptions.RayTaskError: ray_worker (pid=22136, host=ubuntu-gpu-server)
  File "/home/mengzl/miniconda3/envs/neurocuts/lib/python3.5/site-packages/ray/rllib/agents/trainer.py", line 367, in train
    raise e
  File "/home/mengzl/miniconda3/envs/neurocuts/lib/python3.5/site-packages/ray/rllib/agents/trainer.py", line 353, in train
    result = Trainable.train(self)
  File "/home/mengzl/miniconda3/envs/neurocuts/lib/python3.5/site-packages/ray/tune/trainable.py", line 150, in train
    result = self._train()
  File "/home/mengzl/miniconda3/envs/neurocuts/lib/python3.5/site-packages/ray/rllib/agents/trainer_template.py", line 126, in _train
    fetches = self.optimizer.step()
  File "/home/mengzl/miniconda3/envs/neurocuts/lib/python3.5/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 141, in step
    samples.append(self.workers.local_worker().sample())
  File "/home/mengzl/miniconda3/envs/neurocuts/lib/python3.5/site-packages/ray/rllib/evaluation/rollout_worker.py", line 430, in sample
    batches = [self.input_reader.next()]
  File "/home/mengzl/miniconda3/envs/neurocuts/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 60, in next
    batches = [self.get_data()]
  File "/home/mengzl/miniconda3/envs/neurocuts/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 101, in get_data
    item = next(self.rollout_provider)
  File "/home/mengzl/miniconda3/envs/neurocuts/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 338, in _env_runner
    base_env.send_actions(actions_to_send)
  File "/home/mengzl/miniconda3/envs/neurocuts/lib/python3.5/site-packages/ray/rllib/env/base_env.py", line 382, in send_actions
    obs, rewards, dones, infos = env.step(agent_dict)
  File "/home/mengzl/neurocuts/neurocuts_env.py", line 185, in step
    advantages, stats = self.compute_gae(self.depth_weight)
  File "/home/mengzl/neurocuts/neurocuts_env.py", line 280, in compute_gae
    vf = policy.sess.run(policy.value_function, feed_dict)
AttributeError: 'PPOTFPolicy' object has no attribute 'sess'
```
I'm running on Python 3.5, Ray 0.7.2. Thanks in advance!

**Comment by Mingkai-Tong** [comment]
hello,I also have this problem by using Python 3.6, Ray 0.7.2. Do you have the answer to this question now?

**Comment by mengzili** [comment]
> 
> 
> hello,I also have this problem by using Python 3.6, Ray 0.7.2. Do you have the answer to this question now?

Not yet... I guess maybe it's a compatibility issue caused by Ray? I went through several recent versions of Ray but didn't see the usage of `PPOTFPolicy.sess`. Do you have any idea?

**Comment by Mingkai-Tong** [comment]
unfortunately not. I tried all versions of ray 0.7.x but failed.

**Comment by Changgang-Zheng** [comment]
For run the neurocuts codes. tensorflow 1.13.1 and ray 0.7.6 can be used.
